# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: 移至 _data/i18n.yml
# subtitle: 移至 _data/i18n.yml
# subtitle2: 移至 _data/i18n.yml
# name: 移至 _data/i18n.yml
# description: 移至 _data/i18n.yml
keywords: Java,C/C++,数据结构,生活故事,NAS,装机,开发者,编程,代码,开源,效率,Developer,Programmer,Coder,Geek.

# 通用设置相关
email: meetyifan@gmail.com
encoding: "utf-8"
repository: oreoft/oreoft.github.io
url: https://www.someget.cn
github_url: https://github.com/oreoft
enforce_ssl: https://www.someget.cn

# OSS 图片优化配置
oss_optimization:
  enable: true
  domain: "mypicgogo.oss-cn-hangzhou.aliyuncs.com"
  # 注意：参数前面不需要带 '?'
  params: "x-oss-process=image/auto-orient,1/resize,w_1200,limit_0/format,webp/quality,Q_80"

## Gem的插件
plugins:
  - jekyll-geo-pattern
  - rouge
  - kramdown

# 分页配置
# 每页显示的文章数量（中英文共用）
posts_per_page: 6

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
host: 127.0.0.1
port: 4000
source:      .
destination: ./_site
quiet:    false
defaults: []

# 插件相关
kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge
syntax_highlighter_opts:
   coderay_line_numbers:  nil


# 下面基本都是页面配置
# Navigation. top menu list
# 菜单内容已移至 _data/i18n.yml，此处保留配置项以备将来扩展
menus: []

# Navigation. main menu list
navs: []


# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show




# labels. my blog key words
labels:
  -
    href: “”
    label:   
    target: _self
  -
    href: “”
    label: 
    target: _self
  -
    href: “”
    label: 
    target: _blank

# selected articles
classes:
  zh:
    - href: /other/2021/01/11/510smin_1
      name: 2021年买的最值的东西
      describe: 联想510smini小主机
#    - href: /linux/2021/06/20/jekyll_install
#      name: Linux安装jekyll
#      describe: 自己建站的一些经验
    - href: /other/2021/10/05/coding_name01
      name: 工程实践中关于命名那些事
      describe: 自己总结的命名规范希望能给大家参考
    - href: /other/2020/10/03/m73
      name: 联想m73黑苹果折腾记
      describe: 为什么电子垃圾往往会有第二春
  en:
    - href: /en/java/2022/05/15/cache-anno01.html
      name: Data automatic caching annotations
      describe: Automatic cache annotation based on AOP implementation

#    - href: /en/other/2021/10/05/coding_name01
#      name: Naming in Engineering Practice
#      describe: The naming convention for coding summarized by myself hopefully can give you a reference
#
#    - href: /en/other/2020/10/03/m73
#      name: Lenovo m73 black apple toss
#      describe: Why e-waste often has a second life


# soft
soft: 
  en:
    - html_url: https://github.com/oreoft/cache-anno
      name: Cache-anno
      description: Automatically caching method data annotations
  zh:
    - html_url: https://github.com/oreoft/cache-anno
      name: Cache-anno
      description: 自动缓存方法数据注解

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml
