# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title_en: Oreoft
subtitle_en: Believe in the light and become the light
subtitle2_en: There are no reason why you cannot become an expert in the field you love
name_en: Oreoft
description_en: description
keywords_ne: Developer, Programmer, increase-efficiency, Geek, Coder

title:  没有气的汽水
subtitle: 是折腾，也是热爱呀
subtitle2: 你没有理由不成为你热爱领域的专家
name: 没有气的汽水
description:
keywords: Java,C/C++,数据结构,生活故事,NAS,装机,开发者,编程,代码,开源,效率,Developer,Programmer,Coder,Geek.

# 通用设置相关
email: meetyifan@gmail.com
encoding: "utf-8"
repository: oreoft/oreoft.github.io
url: https://www.someget.cn
github_url: https://github.com/oreoft
enforce_ssl: https://www.someget.cn

# OSS 图片优化配置
oss_optimization:
  enable: true
  domain: "mypicgogo.oss-cn-hangzhou.aliyuncs.com"
  # 注意：参数前面不需要带 '?'
  params: "x-oss-process=image/auto-orient,1/resize,w_1200,limit_0/format,webp/quality,Q_80"

## Gem的插件
plugins:
  - jekyll-geo-pattern
  - rouge
  - kramdown

# 分页配置
# 每页显示的文章数量（中英文共用）
posts_per_page: 6

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
host: 127.0.0.1
port: 4000
source:      .
destination: ./_site
quiet:    false
defaults: []

# 插件相关
kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge
syntax_highlighter_opts:
   coderay_line_numbers:  nil


# 下面基本都是页面配置
# Navigation. top menu list
# _blank表示新网页，_self小时在本页
menus:
  en:
    -
      href: /en
      label: Home
      target: _self

    -
      href: /en/about
      label: About
      target: _self

    -
      href: /en/link
      label: FriendLink
      target: _self

    -
      href: /en/archives
      label: Archives
      target: _self
  zh:
      - href: /
        label: Home
        target: _self

      - href: /about
        label: About
        target: _self

      - href: /link
        label: FriendLink
        target: _self

      - href: /archives
        label: Archives
        target: _self

# Navigation. main menu list
# subnav可以加二级分类
navs:
  en:
    - href: /en/code
      label: Code
      target: _self

    - href: /en/base
      label: Base
      target: _self

    - href: /en/tools
      label: Tools
      target: _self

    - href: /en/other
      label: Other
      target: _self
      subnav:
        - subHref: /en/linux
          subLabel: Linux
        - subHref: /en/middleware
          subLabel: Middleware

  zh:
    - href: /code
      label: Code
      target: _self
#      subnav:
#        - subHref: /zh/java
#          subLabel: Java
#        - subHref: /zh/spring_boot
#          subLabel: Spring Boot

    - href: /base
      label: Base
      target: _self
#      subnav:
#        - subHref: /zh/cc
#          subLabel: 通俗计组
#        - subHref: /zh/ds
#          subLabel: 数据结构
#        - subHref: /zh/cn
#          subLabel: 计算机网络
        # -
        #   subHref: /ee
        #   subLabel: 电工知识
        # -
        #   subHref: recommend
        #   subLabel: 软件推荐

    - href: /tools
      label: Tools
      target: _self
    - href: /other
      label: Other
      target: _self
      subnav:
        - subHref: /linux
          subLabel: Linux
        - subHref: /middleware
          subLabel: Middleware


# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show




# labels. my blog key words
labels:
  -
    href: “”
    label:   
    target: _self
  -
    href: “”
    label: 
    target: _self
  -
    href: “”
    label: 
    target: _blank

# selected articles
classes:
  zh:
    - href: /other/2021/01/11/510smin_1
      name: 2021年买的最值的东西
      describe: 联想510smini小主机
#    - href: /linux/2021/06/20/jekyll_install
#      name: Linux安装jekyll
#      describe: 自己建站的一些经验
    - href: /other/2021/10/05/coding_name01
      name: 工程实践中关于命名那些事
      describe: 自己总结的命名规范希望能给大家参考
    - href: /other/2020/10/03/m73
      name: 联想m73黑苹果折腾记
      describe: 为什么电子垃圾往往会有第二春
  en:
    - href: /en/java/2022/05/15/cache-anno01.html
      name: Data automatic caching annotations
      describe: Automatic cache annotation based on AOP implementation

#    - href: /en/other/2021/10/05/coding_name01
#      name: Naming in Engineering Practice
#      describe: The naming convention for coding summarized by myself hopefully can give you a reference
#
#    - href: /en/other/2020/10/03/m73
#      name: Lenovo m73 black apple toss
#      describe: Why e-waste often has a second life


# soft
soft: 
  en:
    - html_url: https://github.com/oreoft/cache-anno
      name: Cache-anno
      description: Automatically caching method data annotations
  zh:
    - html_url: https://github.com/oreoft/cache-anno
      name: Cache-anno
      description: 自动缓存方法数据注解

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml
